In [2]:
import numpy as np
list_ = [ '1' , '2' , '3', '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Print the data types of list_ and array_list
print(f"The data type of list_ is: {type(list_)}")
print(f"The data type of array_list is: {type(array_list)}")


The data type of list_ is: <class 'list'>
The data type of array_list is: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
# Print the data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print the data types of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Data type of elements after changing array_list to integers

In [5]:
array_list = np.array(object = list_, dtype = int)

# Print the data types of each element in list_
print("Data types of elements in list_ after conversion:")
for element in list_:
    print(type(element))

# Print the data types of each element in array_list after conversion
print("Data types of elements in array_list after conversion:")
for element in array_list:
    print(type(element))


Data types of elements in list_ after conversion:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list after conversion:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# Print the shape and size of num_array
print(f"The shape of num_array is: {num_array.shape}")
print(f"The size of num_array is: {num_array.size}")


The shape of num_array is: (2, 3)
The size of num_array is: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [8]:
# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))
print("3x3 matrix of zeros:")
print(zero_matrix)


3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
